In [2]:
import pandas as pd
df = pd.read_csv("raw_data.csv")

In [1]:
df

NameError: name 'df' is not defined

In [2]:
df.isnull()

NameError: name 'df' is not defined

In [7]:
df.isnull().sum() # total missing values

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [8]:
df.dropna()  #it drops row all the missing value

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [10]:
df.dropna(axis=1)  #column drop

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [14]:
df.fillna(0)
df["age"].fillna(0)

0     29.0
1     29.0
2      0.0
3      0.0
4     34.0
5     27.0
6     45.0
7     38.0
8     29.0
9      0.0
10    31.0
Name: age, dtype: float64

In [17]:
age_mean = df["age"].mean()
cleaned_data = df.copy()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [18]:
df.ffill() #forward fill

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [19]:
#backward fill
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [24]:
#handle duplicates
df.duplicated()
df["country"].duplicated()
df[["country","gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [26]:
df.drop_duplicates()
df2 = df.copy()
df.drop_duplicates(inplace=True)

In [39]:
df

0     29
2      0
3      0
4     34
5     27
6     45
7     38
8     29
9      0
10    31
Name: age, dtype: int64

In [30]:
#handleing data types
df.dtypes
df2 = df.copy()

df2 =df2.fillna(0)

In [34]:
df2=df2["age"].astype("int64").copy()
df2.dtypes

dtype('int64')

In [36]:
df2

0     29
2      0
3      0
4     34
5     27
6     45
7     38
8     29
9      0
10    31
Name: age, dtype: int64

In [37]:
df2

0     29
2      0
3      0
4     34
5     27
6     45
7     38
8     29
9      0
10    31
Name: age, dtype: int64

In [38]:
df

0     29
2      0
3      0
4     34
5     27
6     45
7     38
8     29
9      0
10    31
Name: age, dtype: int64

In [40]:
#date time 
df9 = pd.read_csv("globalAirQuality.csv")

In [41]:
df9

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [15]:
import pandas as pd 
df9 = pd.read_csv("globalAirQuality.csv")
date_str = "2026-12-8"
type(date_str)

str

In [16]:
date_str = pd.Series([pd.to_datetime("2026-12-8")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [17]:
df9["timestamp"]=pd.to_datetime(df9["timestamp"])
df["timestamp"].dtype

dtype('<M8[ns]')

In [19]:
#handling strings
df = pd.read_csv("raw_data.csv")

In [20]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [22]:
df["gender"].str.capitalize() 
df["gender"].str.upper() 
df["gender"].str.lower()

0        male
1        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: object

In [44]:
#split method
var= df["gender"].str.split(" ")

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
Name: gender, dtype: float64

In [38]:
df["country"].str.contains("US")

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object