In [3]:
import pandas as pd

In [20]:
info = {
    "name" : ["Dhruv","pankhuri", "vasu"],
     "CGPA" : [9.5,9.8,10]
}
df = pd.DataFrame(info) 
print(df)

       name  CGPA
0     Dhruv   9.5
1  pankhuri   9.8
2      vasu  10.0

In [19]:
df

       name  CGPA
0     Dhruv   9.5
1  pankhuri   9.8
2      vasu  10.0

In [23]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))
# index
print(s[0])   #index based access
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [32]:
age = pd.Series([23,34,45,12,19], index=["Dhruv","vasu","tanay","shourya","pankhuri"])
print(age)
print(age["Dhruv"])  #label based access
print(age.index)

Dhruv       23
vasu        34
tanay       45
shourya     12
pankhuri    19
dtype: int64
23
Index(['Dhruv', 'vasu', 'tanay', 'shourya', 'pankhuri'], dtype='object')

In [38]:
s1 = pd.Series([1,3,5,6,7])
s2 = pd.Series([3,5,6,8,9])
print(s1 + s2)    #vectorized operation
s1[0] = 100   #index value mutuble
print(s1 + s2) 
ch=s1.drop([0])
print(ch)
print(s1)

0     4
1     8
2    11
3    14
4    16
dtype: int64
0    103
1      8
2     11
3     14
4     16
dtype: int64
1    3
2    5
3    6
4    7
dtype: int64
0    100
1      3
2      5
3      6
4      7
dtype: int64

In [42]:
#Data frame
#creating Data Frame from  dictionary
info = {
    "name" : ["Dhruv","pankhuri", "vasu"],
    "Age" :[19,20 ,18],
     "CGPA" : [9.5,9.8,10]
}
df = pd.DataFrame(info) 
print(df, type(df))

print(df.index)
print(df.columns)

       name  Age  CGPA
0     Dhruv   19   9.5
1  pankhuri   20   9.8
2      vasu   18  10.0 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['name', 'Age', 'CGPA'], dtype='object')

In [41]:
df

       name  Age  CGPA
0     Dhruv   19   9.5
1  pankhuri   20   9.8
2      vasu   18  10.0

In [45]:
#Data Frame (list in list method)

df = pd.DataFrame([["Dhruv",19],["pankhuri",18],["vasu", 20]],columns = ["name","age"])
print(df)

       name  age
0     Dhruv   19
1  pankhuri   18
2      vasu   20

In [47]:
#Data Frame (np.array method)
import numpy as np
np_arr = np.array([[1,2,3],[2,4,6]])
df = pd.DataFrame(np_arr, columns= ["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  2  4  6

In [2]:
#csv data
import pandas as pd
df = pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [8]:
#Methods 
df.head() #print initial 5 rows
          #if u insert any nnumber in the (no of rows to be printed)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [9]:
df.tail() #trailing 5 rows 
          # #if u insert any nnumber in the (no of rows to be printed)

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [10]:
df.sample() #random row 
 #if u insert any nnumber in the (no of rows to be printed)

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000

In [11]:
df.info()  #data summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [14]:
df.shape #retun the tuple of row and column

(10, 5)

In [15]:
df.describe()  #print min, max std,mean, count and many more

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [17]:
df.columns  #not callable by ()

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [18]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [19]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000