In [1]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:
df = datasets.load_iris(as_frame=True).frame

In [3]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [4]:
df.isnull().sum()
df.shape

(150, 5)

In [5]:
x = df.drop("target",axis=1)
y =df["target"]

In [6]:
x.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
#Scaling is necessary in svm
x_train,x_test,y_train,y_test = train_test_split(
   x,y,test_size=0.3,random_state = 42,stratify=y
)

In [8]:
x_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [11]:
from sklearn.preprocessing import StandardScaler
sclar = StandardScaler()
x_scaled_train=sclar.fit_transform(x_train)
x_test_scaled = sclar.transform(x_test)

In [20]:
# Model
svc = SVC()
svc.fit(x_scaled_train,y_train)
y_pred = svc.predict(x_test_scaled)

In [28]:
from sklearn.metrics import accuracy_score
print("accuracy:",accuracy_score(y_test,y_pred))
print("classification report:",classification_report(y_test,y_pred))

accuracy: 0.9333333333333333
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [33]:
svc = SVC(kernel = "linear")
svc = SVC()
svc.fit(x_scaled_train,y_train)
y_predi = svc.predict(x_test_scaled)
print("accuracy:",accuracy_score(y_test,y_predi))
print("classification report:",classification_report(y_test,y_pred))

accuracy: 0.9333333333333333
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45